.TH "lmcb" 3 "Thu Apr 7 2016" "MPX Group 9 - Phishing for Cookies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lmcb \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mcb\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBallocated\fP"
.br
.ti -1c
.RI "u32int \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This lmcb structure is a Limtited Memory Control Block\&. This block corresponds to a specific Complete Memory Control Block, and contains the same size and allocated state\&. This block consists of the following variables: int allocated - state of the block, allocated (1), and not allocated (0) int size - the size of the Memory Control Block 

.SH "Author"
.PP 
Generated automatically by Doxygen for MPX Group 9 - Phishing for Cookies from the source code\&.
