.TH "queue" 3 "Thu Apr 7 2016" "MPX Group 9 - Phishing for Cookies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
queue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queues\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBpcb\fP * \fBhead\fP"
.br
.ti -1c
.RI "\fBpcb\fP * \fBtail\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The queue structure is used to house the number of elements, and the first and last node in the queue\&. This structure consists of an int for the number of nodes, and a pcb pointer to the head and tail of the queue\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for MPX Group 9 - Phishing for Cookies from the source code\&.
