.TH "modules Directory Reference" 3 "Fri Mar 18 2016" "MPX Group 9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommhand\&.c\fP"
.br
.ti -1c
.RI "file \fBcommhand\&.h\fP"
.br
.ti -1c
.RI "file \fBdate\&.c\fP"
.br
.ti -1c
.RI "file \fBdate\&.h\fP"
.br
.ti -1c
.RI "file \fBextFuncs\&.c\fP"
.br
.ti -1c
.RI "file \fBextFuncs\&.h\fP"
.br
.ti -1c
.RI "file \fBhelp\&.c\fP"
.br
.ti -1c
.RI "file \fBhelp\&.h\fP"
.br
.ti -1c
.RI "file \fBmpx_supt\&.c\fP"
.br
.ti -1c
.RI "file \fBmpx_supt\&.h\fP"
.br
.ti -1c
.RI "file \fBprocessControl\&.c\fP"
.br
.ti -1c
.RI "file \fBprocessControl\&.h\fP"
.br
.ti -1c
.RI "file \fBqueues\&.c\fP"
.br
.ti -1c
.RI "file \fBqueues\&.h\fP"
.br
.ti -1c
.RI "file \fBr3procs\&.c\fP"
.br
.ti -1c
.RI "file \fBr3procs\&.h\fP"
.br
.ti -1c
.RI "file \fBsyscall\&.c\fP"
.br
.ti -1c
.RI "file \fBsyscall\&.h\fP"
.br
.ti -1c
.RI "file \fBversion\&.c\fP"
.br
.ti -1c
.RI "file \fBversion\&.h\fP"
.br
.in -1c
