.TH "modules/date.h" 3 "Fri Mar 18 2016" "MPX Group 9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/date.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <system\&.h>\fP
.br
\fC#include <core/serial\&.h>\fP
.br
\fC#include <core/io\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdate\fP (char *args)"
.br
.ti -1c
.RI "unsigned char \fBhex2ASCII\fP (unsigned char dec)"
.br
.ti -1c
.RI "unsigned char \fBASCII2hex\fP (char *ASCII)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MPX Group 9 from the source code\&.
