.TH "modules/help.h" 3 "Fri Mar 18 2016" "MPX Group 9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/help.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <system\&.h>\fP
.br
\fC#include <core/serial\&.h>\fP
.br
\fC#include <core/io\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhelp\fP (char *args)"
.br
.ti -1c
.RI "void \fBversion_help\fP ()"
.br
.ti -1c
.RI "void \fBshutdown_help\fP ()"
.br
.ti -1c
.RI "void \fBdate_help\fP ()"
.br
.ti -1c
.RI "void \fBpcb_help\fP ()"
.br
.ti -1c
.RI "void \fByield_help\fP ()"
.br
.ti -1c
.RI "void \fBloadr3_help\fP ()"
.br
.ti -1c
.RI "void \fBdefault_help\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MPX Group 9 from the source code\&.
