.TH "modules/r3procs.h" 3 "Fri Mar 18 2016" "MPX Group 9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modules/r3procs.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <system\&.h>\fP
.br
\fC#include <core/serial\&.h>\fP
.br
\fC#include 'mpx_supt\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRC_1\fP   1"
.br
.ti -1c
.RI "#define \fBRC_2\fP   2"
.br
.ti -1c
.RI "#define \fBRC_3\fP   3"
.br
.ti -1c
.RI "#define \fBRC_4\fP   4"
.br
.ti -1c
.RI "#define \fBRC_5\fP   5"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBproc1\fP ()"
.br
.ti -1c
.RI "void \fBproc2\fP ()"
.br
.ti -1c
.RI "void \fBproc3\fP ()"
.br
.ti -1c
.RI "void \fBproc4\fP ()"
.br
.ti -1c
.RI "void \fBproc5\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MPX Group 9 from the source code\&.
